nodeLinker: node-modules

packageExtensions:

  "@nestjs/common@*":
    peerDependencies:
      "reflect-metadata": "*"
      "rxjs": "*"
      "class-validator": "*"
    peerDependenciesMeta:
      "reflect-metadata": { "optional": true }
      "rxjs": { "optional": true }

  "@nestjs/core@*":
    peerDependencies:
      "rxjs": "*"
      "reflect-metadata": "*"
    peerDependenciesMeta:
      "rxjs": { "optional": true }
      "reflect-metadata": { "optional": true }
